apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    # app.kubernetes.io/name: MyApp
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
