apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    # app.kubernetes.io/name: MyApp
    run: nginx-deployment
  ports:
    - protocol: TCP
      port: 81
      targetPort: 80
